/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2022-02-03 06:43:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.fragment;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" <!-- Sidebar -->\r\n");
      out.write(" <ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\" id=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("     <!-- Sidebar - Brand -->\r\n");
      out.write("     <a class=\"sidebar-brand d-flex align-items-center justify-content-center\" href=\"index.html\">\r\n");
      out.write("         <div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("             <i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"sidebar-brand-text mx-3\">SB Admin <sup>2</sup></div>\r\n");
      out.write("     </a>\r\n");
      out.write("\r\n");
      out.write("     <!-- Divider -->\r\n");
      out.write("     <hr class=\"sidebar-divider my-0\">\r\n");
      out.write("\r\n");
      out.write("     <!-- Nav Item - Dashboard -->\r\n");
      out.write("     <li class=\"nav-item active\">\r\n");
      out.write("         <a class=\"nav-link\" href=\"index.html\">\r\n");
      out.write("             <i class=\"fas fa-fw fa-tachometer-alt\"></i>\r\n");
      out.write("             <span>Dashboard</span></a>\r\n");
      out.write("     </li>\r\n");
      out.write("\r\n");
      out.write("     <!-- Divider -->\r\n");
      out.write("     <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("     <!-- Heading -->\r\n");
      out.write("     <div class=\"sidebar-heading\">\r\n");
      out.write("         Interface\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("     <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("     <li class=\"nav-item\">\r\n");
      out.write("         <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseTwo\"\r\n");
      out.write("             aria-expanded=\"true\" aria-controls=\"collapseTwo\">\r\n");
      out.write("             <i class=\"fas fa-fw fa-cog\"></i>\r\n");
      out.write("             <span>Components</span>\r\n");
      out.write("         </a>\r\n");
      out.write("         <div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("             <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                 <h6 class=\"collapse-header\">Custom Components:</h6>\r\n");
      out.write("                 <a class=\"collapse-item\" href=\"buttons.html\">Buttons</a>\r\n");
      out.write("                 <a class=\"collapse-item\" href=\"cards.html\">Cards</a>\r\n");
      out.write("             </div>\r\n");
      out.write("         </div>\r\n");
      out.write("     </li>\r\n");
      out.write("\r\n");
      out.write("     <!-- Nav Item - Utilities Collapse Menu -->\r\n");
      out.write("     <li class=\"nav-item\">\r\n");
      out.write("         <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseUtilities\"\r\n");
      out.write("             aria-expanded=\"true\" aria-controls=\"collapseUtilities\">\r\n");
      out.write("             <i class=\"fas fa-fw fa-wrench\"></i>\r\n");
      out.write("             <span>Utilities</span>\r\n");
      out.write("         </a>\r\n");
      out.write("         <div id=\"collapseUtilities\" class=\"collapse\" aria-labelledby=\"headingUtilities\"\r\n");
      out.write("             data-parent=\"#accordionSidebar\">\r\n");
      out.write("             <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                 <h6 class=\"collapse-header\">Custom Utilities:</h6>\r\n");
      out.write("                 <a class=\"collapse-item\" href=\"utilities-color.html\">Colors</a>\r\n");
      out.write("                 <a class=\"collapse-item\" href=\"utilities-border.html\">Borders</a>\r\n");
      out.write("                 <a class=\"collapse-item\" href=\"utilities-animation.html\">Animations</a>\r\n");
      out.write("                 <a class=\"collapse-item\" href=\"utilities-other.html\">Other</a>\r\n");
      out.write("             </div>\r\n");
      out.write("         </div>\r\n");
      out.write("     </li>\r\n");
      out.write("\r\n");
      out.write("     <!-- Divider -->\r\n");
      out.write("     <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("     <!-- Heading -->\r\n");
      out.write("     <div class=\"sidebar-heading\">\r\n");
      out.write("         Addons\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("     <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("     <li class=\"nav-item\">\r\n");
      out.write("         <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapsePages\"\r\n");
      out.write("             aria-expanded=\"true\" aria-controls=\"collapsePages\">\r\n");
      out.write("             <i class=\"fas fa-fw fa-folder\"></i>\r\n");
      out.write("             <span>Pages</span>\r\n");
      out.write("         </a>\r\n");
      out.write("         <div id=\"collapsePages\" class=\"collapse\" aria-labelledby=\"headingPages\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("             <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                 <h6 class=\"collapse-header\">Login Screens:</h6>\r\n");
      out.write("                 <a class=\"collapse-item\" href=\"login.ldh\">Login</a>\r\n");
      out.write("                 <a class=\"collapse-item\" href=\"register.ldh\">Register</a>\r\n");
      out.write("                 <a class=\"collapse-item\" href=\"forgot-password.html\">Forgot Password</a>\r\n");
      out.write("                 <div class=\"collapse-divider\"></div>\r\n");
      out.write("                 <h6 class=\"collapse-header\">Other Pages:</h6>\r\n");
      out.write("                 <a class=\"collapse-item\" href=\"404.html\">404 Page</a>\r\n");
      out.write("                 <a class=\"collapse-item\" href=\"blank.html\">Blank Page</a>\r\n");
      out.write("             </div>\r\n");
      out.write("         </div>\r\n");
      out.write("     </li>\r\n");
      out.write("\r\n");
      out.write("     <!-- Nav Item - Charts -->\r\n");
      out.write("     <li class=\"nav-item\">\r\n");
      out.write("         <a class=\"nav-link\" href=\"charts.html\">\r\n");
      out.write("             <i class=\"fas fa-fw fa-chart-area\"></i>\r\n");
      out.write("             <span>Charts</span></a>\r\n");
      out.write("     </li>\r\n");
      out.write("\r\n");
      out.write("     <!-- Nav Item - Tables -->\r\n");
      out.write("     <li class=\"nav-item\">\r\n");
      out.write("         <a class=\"nav-link\" href=\"tables.html\">\r\n");
      out.write("             <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("             <span>Tables</span></a>\r\n");
      out.write("     </li>\r\n");
      out.write("\r\n");
      out.write("     <!-- Divider -->\r\n");
      out.write("     <hr class=\"sidebar-divider d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("     <!-- Sidebar Toggler (Sidebar) -->\r\n");
      out.write("     <div class=\"text-center d-none d-md-inline\">\r\n");
      out.write("         <button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("     <!-- Sidebar Message -->\r\n");
      out.write("     <div class=\"sidebar-card d-none d-lg-flex\">\r\n");
      out.write("         <img class=\"sidebar-card-illustration mb-2\" src=\"img/undraw_rocket.svg\" alt=\"...\">\r\n");
      out.write("         <p class=\"text-center mb-2\"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>\r\n");
      out.write("         <a class=\"btn btn-success btn-sm\" href=\"https://startbootstrap.com/theme/sb-admin-pro\">Upgrade to Pro!</a>\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write(" </ul>\r\n");
      out.write(" <!-- End of Sidebar -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
